# Generated by Django 4.2.5 on 2023-09-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_care_hub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('mileage', models.PositiveIntegerField()),
                ('vin', models.CharField(blank=True, max_length=17, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
