# Generated by Django 4.2.5 on 2023-09-07 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_care_hub', '0003_vehicle_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='user',
        ),
    ]
